const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Generates a professional Niche Blueprint PDF
 * @param {string} keyword - Niche keyword
 * @param {string} content - Markdown/Text content from Gemini
 * @param {string} outputPath - Where to save the PDF
 */
async function createNichePDF(keyword, content, outputPath) {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({
            margin: 50,
            size: 'A4',
            bufferPages: true
        });

        const stream = fs.createWriteStream(outputPath);
        doc.pipe(stream);

        // Header
        doc.fillColor('#F4A81D').fontSize(26).text('NicheReport.ai', { align: 'center' });
        doc.fillColor('#333').fontSize(32).text(`The Ultimate Blueprint: ${keyword}`, { align: 'center' });
        doc.moveDown(2);

        // Table of Contents styling helper
        const addSectionHeader = (text) => {
            doc.moveDown();
            doc.fillColor('#F4A81D').fontSize(18).text(text.toUpperCase(), { underline: true });
            doc.moveDown(0.5);
            doc.fillColor('#444').fontSize(12);
        };

        // Split content by headers or lines and render
        const lines = content.split('\n');
        lines.forEach(line => {
            if (line.startsWith('# ')) {
                doc.addPage();
                doc.fillColor('#F4A81D').fontSize(22).text(line.replace('# ', ''), { align: 'left' });
                doc.moveDown();
            } else if (line.startsWith('## ')) {
                addSectionHeader(line.replace('## ', ''));
            } else if (line.trim() === '---') {
                doc.moveDown();
                doc.strokeColor('#eee').moveTo(50, doc.y).lineTo(550, doc.y).stroke();
                doc.moveDown();
            } else if (line.trim()) {
                doc.fillColor('#444').fontSize(12).text(line.trim(), {
                    align: 'justify',
                    lineGap: 2
                });
            } else {
                doc.moveDown(0.5);
            }
        });

        // Footer on every page
        const range = doc.bufferedPageRange();
        for (let i = 0; i < range.count; i++) {
            doc.switchToPage(i);
            doc.fillColor('#aaa').fontSize(10).text(
                `Generated by NicheReport.ai | Page ${i + 1} of ${range.count}`,
                50,
                doc.page.height - 50,
                { align: 'center' }
            );
        }

        doc.end();
        stream.on('finish', () => resolve(outputPath));
        stream.on('error', reject);
    });
}

module.exports = { createNichePDF };
