const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Generates a professional Niche Blueprint PDF
 * @param {string} keyword - Niche keyword
 * @param {string} content - Markdown/Text content from Gemini
 * @param {string} outputPath - Where to save the PDF
 */
async function createNichePDF(keyword, content, outputPath) {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({
            margin: 50,
            size: 'A4',
            bufferPages: true
        });

        const stream = fs.createWriteStream(outputPath);
        doc.pipe(stream);

        // Header
        doc.fillColor('#F4A81D').fontSize(26).text('NicheReport.ai', { align: 'center' });
        doc.fillColor('#333').fontSize(32).text(`The Ultimate Blueprint: ${keyword}`, { align: 'center' });
        doc.moveDown(2);

        // Table of Contents styling helper
        const addSectionHeader = (text) => {
            doc.moveDown();
            doc.fillColor('#F4A81D').fontSize(18).text(text.toUpperCase(), { underline: true });
            doc.moveDown(0.5);
            doc.fillColor('#444').fontSize(12);
        };

        // Split content by headers or lines and render
        const lines = content.split('\n');
        lines.forEach(line => {
            if (line.startsWith('# ')) {
                doc.addPage();
                doc.fillColor('#F4A81D').fontSize(24).font('Helvetica-Bold').text(line.replace('# ', ''), { align: 'left' });
                doc.font('Helvetica').moveDown();
            } else if (line.startsWith('## ')) {
                addSectionHeader(line.replace('## ', ''));
            } else if (line.startsWith('### ')) {
                doc.moveDown(0.5);
                doc.fillColor('#1B2A40').fontSize(14).font('Helvetica-Bold').text(line.replace('### ', ''));
                doc.font('Helvetica').moveDown(0.2);
            } else if (line.trim() === '---') {
                doc.moveDown();
                doc.strokeColor('#eee').lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
                doc.moveDown();
            } else if (line.trim().startsWith('- ') || line.trim().startsWith('* ')) {
                const bulletText = line.trim().substring(2);
                doc.fillColor('#444').fontSize(12).font('Helvetica').text('• ' + bulletText, {
                    indent: 20,
                    lineGap: 2
                });
            } else if (line.trim()) {
                // Basic Bold support within a line: **text**
                const text = line.trim();
                if (text.includes('**')) {
                    const parts = text.split('**');
                    doc.fillColor('#444').fontSize(12).font('Helvetica');
                    
                    parts.forEach((part, i) => {
                        if (i % 2 === 1) {
                            doc.font('Helvetica-Bold').text(part, { continued: i < parts.length - 1 });
                        } else {
                            doc.font('Helvetica').text(part, { continued: i < parts.length - 1 });
                        }
                    });
                    doc.text(''); // end line
                } else {
                    doc.fillColor('#444').fontSize(12).font('Helvetica').text(text, {
                        align: 'justify',
                        lineGap: 2
                    });
                }
            } else {
                doc.moveDown(0.5);
            }
        });

        // Footer on every page
        const range = doc.bufferedPageRange();
        for (let i = 0; i < range.count; i++) {
            doc.switchToPage(i);
            doc.fillColor('#aaa').fontSize(10).text(
                `Generated by NicheReport.ai | Page ${i + 1} of ${range.count}`,
                50,
                doc.page.height - 50,
                { align: 'center' }
            );
        }

        doc.end();
        stream.on('finish', () => resolve(outputPath));
        stream.on('error', reject);
    });
}

module.exports = { createNichePDF };
